export { default as Header } from './header/header'
export { default as Footer } from './footer/footer'
export { default as Button } from './button/button'
export { default as BgComponent } from './bg_component/bg_component'
export { default as BgAnimation } from './bg_animation/bg_animation'
export { default as Title } from './title/title'
export { default as HomeCard } from './home_card/homeCard'
export { default as Dots } from './dots/dots'